name = "document-requester"
main = "src/index.ts"
compatibility_date = "2023-01-22"

[[r2_buckets]]
binding = 'DOCUMENT_BUCKET'
# note: this is required: ✘ [ERROR] In development, you should use a separate r2 bucket than the one you'd use in production. Please create a new r2 bucket with "wrangler r2 bucket create <name>" and add its name as preview_bucket_name to the r2_buckets "RESUME_BUCKET" in your wrangler.toml
preview_bucket_name = 'documents-test'
bucket_name = 'documents'

[[d1_databases]]
binding = 'DB'
database_name = 'document-requester'
database_id = '62d70739-9adb-4891-b314-49404a734129'
# note: this is required: ✘ [ERROR] In development, you should use a separate D1 database than the one you'd use in production. Please create a new D1 database with "wrangler d1 create <name>" and add its id as preview_database_id to the d1_database "DB" in your wrangler.toml
preview_database_id = '408d9d9c-abeb-4c6c-98e0-21c9d5f22b0d'


[triggers]
# https://crontab.guru/#0_17_*_*_*
crons = ["0 17 * * *"]

[vars]
WORKER_URL='https://document-requester.kory.workers.dev'

# NOTE: this is required for running migrations against the preview database
# [env.dev]
# d1_databases = [ { binding = "DB", database_id = "408d9d9c-abeb-4c6c-98e0-21c9d5f22b0d", database_name = "document-requester-test" }, ]